# Training hyperparameters
LEARNING_RATE = 0.0001
WEIGHT_DECAY = 0.01
BATCH_SIZE = 2
NUM_EPOCHS = 500
LEARNING_RATE = 0.001
DROPOUT_RATE = 0.2
L2_LAMBDA = 0.01

# Dataset
DATA_DIR = "/"

# Compute related
ACCELERATOR = "gpu"
DEVICES = [0]
PRECISION = '16-mixed'
NUM_WORKERS = 1
